library anagrams;

Map<int, List<String>> anagrams = {
4: [
     ['instar', 'santir', 'strain', 'trains'],
     ['denars', 'redans', 'sander', 'snared'],
     ['petrales', 'pleaters', 'prelates', 'replates'],
     ['denser', 'enders', 'resend', 'sender'],
     ['penster', 'present', 'repents', 'serpent'],
     ['averts', 'starve', 'traves', 'vaster'],
     ['detours', 'dourest', 'redouts', 'rousted'],
     ['adheres', 'headers', 'hearsed', 'sheared'],
     ['gingers', 'niggers', 'serging', 'snigger'],
     ['citer', 'recit', 'recti', 'trice'],
     ['cripes', 'precis', 'prices', 'spicer'],
     ['alans', 'anlas', 'nalas', 'nasal'],
     ['armed', 'derma', 'dream', 'madre'],
     ['serve', 'sever', 'veers', 'verse'],
     ['dinar', 'drain', 'nadir', 'ranid'],
     ['pinot', 'pinto', 'piton', 'point'],
     ['dares', 'dears', 'rased', 'reads'],
     ['deary', 'deray', 'rayed', 'ready'],
     ['balmiest', 'bimetals', 'lambiest', 'timbales'],
     ['baritones', 'obtainers', 'reobtains', 'taborines'],
     ['drails', 'lairds', 'liards', 'lidars'],
     ['partans', 'spartan', 'tarpans', 'trapans'],
     ['liter', 'litre', 'relit', 'tiler'],
     ['liers', 'riels', 'riles', 'slier'],
     ['denude', 'dudeen', 'duende', 'endued'],
     ['keens', 'knees', 'skeen', 'skene'],
     ['censored', 'encoders', 'necrosed', 'seconder'],
     ['nerts', 'rents', 'stern', 'terns'],
     ['filers', 'fliers', 'lifers', 'rifles'],
     ['rives', 'siver', 'viers', 'vires'],
     ['hematics', 'mastiche', 'misteach', 'tachisme'],
     ['espials', 'lapises', 'lipases', 'palsies'],
     ['pate', 'peat', 'tape', 'tepa'],
     ['lamister', 'marliest', 'marlites', 'misalter'],
     ['aery', 'eyra', 'yare', 'year'],
     ['argentites', 'estreating', 'integrates', 'interstage'],
     ['darter', 'retard', 'tarred', 'trader'],
     ['maintop', 'ptomain', 'tampion', 'timpano'],
     ['argentic', 'catering', 'creating', 'reacting'],
     ['islet', 'istle', 'stile', 'tiles'],
     ['argles', 'glares', 'lagers', 'larges'],
     ['amender', 'meander', 'reedman', 'renamed'],
     ['girts', 'grist', 'grits', 'trigs'],
     ['asps', 'pass', 'saps', 'spas'],
     ['paws', 'swap', 'waps', 'wasp'],
     ['past', 'pats', 'spat', 'taps'],
     ['atoners', 'santero', 'senator', 'treason'],
     ['eyras', 'resay', 'sayer', 'years'],
     ['aures', 'urase', 'ureas', 'ursae'],
     ['moorworts', 'rootworms', 'tomorrows', 'wormroots'],
     ['caterer', 'recrate', 'retrace', 'terrace'],
     ['lassi', 'sails', 'sials', 'sisal'],
     ['dinars', 'drains', 'nadirs', 'ranids'],
     ['norites', 'oestrin', 'orients', 'stonier'],
     ['agree', 'eager', 'eagre', 'ragee'],
     ['abler', 'baler', 'blare', 'blear'],
     ['artist', 'strait', 'strati', 'traits'],
     ['notal', 'talon', 'tolan', 'tonal'],
     ['colters', 'corslet', 'costrel', 'lectors'],
     ['stickler', 'strickle', 'ticklers', 'trickles'],
     ['brumal', 'labrum', 'lumbar', 'umbral'],
     ['maidens', 'medians', 'medinas', 'sideman'],
     ['halest', 'haslet', 'lathes', 'shelta'],
     ['outgrin', 'outring', 'routing', 'touring'],
     ['lasting', 'salting', 'slating', 'staling'],
     ['abuts', 'tabus', 'tsuba', 'tubas'],
     ['nipa', 'pain', 'pian', 'pina'],
     ['citadel', 'deltaic', 'dialect', 'edictal'],
     ['gamier', 'imager', 'maigre', 'mirage'],
     ['inro', 'iron', 'noir', 'nori'],
     ['ervil', 'liver', 'livre', 'viler'],
     ['antisera', 'ratanies', 'santeria', 'seatrain'],
     ['dedans', 'desand', 'sadden', 'sanded'],
     ['abet', 'bate', 'beat', 'beta'],
     ['ahs', 'ash', 'has', 'sha'],
     ['caste', 'cates', 'cesta', 'taces'],
     ['pastina', 'patinas', 'pinatas', 'taipans'],
     ['caner', 'crane', 'nacre', 'rance'],
     ['nope', 'open', 'peon', 'pone'],
     ['dotier', 'editor', 'rioted', 'triode'],
     ['apses', 'pases', 'passe', 'spaes'],
     ['eclipsers', 'preslices', 'priceless', 'resplices'],
     ['ceramist', 'matrices', 'mistrace', 'scimetar'],
     ['manors', 'ramson', 'ransom', 'romans'],
     ['binder', 'brined', 'inbred', 'rebind'],
     ['berated', 'debater', 'rebated', 'tabered'],
     ['pasture', 'uprates', 'upstare', 'uptears'],
     ['bluster', 'bustler', 'butlers', 'subtler'],
     ['parley', 'pearly', 'player', 'replay'],
     ['otter', 'rotte', 'torte', 'toter'],
     ['derating', 'gradient', 'redating', 'treading'],
     ['isatines', 'sanities', 'sanitise', 'teniasis'],
     ['noter', 'tenor', 'toner', 'trone'],
     ['questor', 'quoters', 'roquets', 'torques'],
     ['botanies', 'botanise', 'niobates', 'obeisant'],
     ['linos', 'lions', 'loins', 'noils'],
     ['hops', 'posh', 'shop', 'soph'],
     ['aspired', 'despair', 'diapers', 'praised'],
     ['oars', 'osar', 'soar', 'sora'],
     ['mangiest', 'mintages', 'misagent', 'steaming'],
     ['gledes', 'gleeds', 'ledges', 'sledge'],
     ['autocrine', 'cautioner', 'cointreau', 'recaution'],
     ['chiros', 'choirs', 'ichors', 'orchis'],
     ['lascars', 'rascals', 'sacrals', 'scalars'],
     ['carless', 'classer', 'scalers', 'scleras'],
     ['cartels', 'clarets', 'crestal', 'scarlet'],
     ['kales', 'lakes', 'leaks', 'slake'],
     ['coinfers', 'conifers', 'forensic', 'fornices'],
     ['dispel', 'lisped', 'sliped', 'spiled'],
     ['panel', 'penal', 'plane', 'plena'],
     ['doer', 'dore', 'redo', 'rode'],
     ['prostie', 'reposit', 'riposte', 'ropiest'],
     ['epos', 'opes', 'peso', 'pose'],
     ['deraign', 'gradine', 'grained', 'reading'],
     ['cheero', 'cohere', 'echoer', 'reecho'],
     ['lanais', 'lianas', 'nasial', 'salina'],
     ['nape', 'neap', 'pane', 'pean'],
     ['padle', 'paled', 'pedal', 'plead'],
     ['laveer', 'leaver', 'reveal', 'vealer'],
     ['rhesus', 'rhuses', 'rushes', 'ushers'],
     ['chitties', 'ethicist', 'itchiest', 'theistic'],
     ['koas', 'oaks', 'okas', 'soak'],
     ['basest', 'basset', 'bastes', 'beasts'],
     ['dentin', 'indent', 'intend', 'tinned'],
     ['corked', 'docker', 'redock', 'rocked'],
     ['orientals', 'relations', 'serotinal', 'tensorial'],
     ['reserve', 'reveres', 'reverse', 'severer'],
     ['antlers', 'rentals', 'saltern', 'sternal'],
     ['diaper', 'paired', 'pardie', 'repaid'],
     ['argus', 'gaurs', 'guars', 'sugar'],
     ['misset', 'smites', 'stimes', 'tmesis'],
     ['warstles', 'wartless', 'wastrels', 'wrastles'],
     ['resins', 'rinses', 'serins', 'sirens'],
     ['centares', 'reascent', 'reenacts', 'sarcenet'],
     ['barest', 'baster', 'breast', 'tabers'],
     ['waister', 'waiters', 'wariest', 'wastrie'],
     ['eloigns', 'legions', 'lingoes', 'longies'],
     ['resilvers', 'riverless', 'silverers', 'sliverers'],
     ['alpines', 'pineals', 'spaniel', 'splenia'],
     ['lenites', 'lisente', 'setline', 'tensile'],
     ['resorts', 'rosters', 'sorters', 'storers'],
     ['inks', 'kins', 'sink', 'skin'],
     ['dreeing', 'energid', 'reeding', 'reigned'],
     ['allergy', 'gallery', 'largely', 'regally'],
     ['hypnotic', 'phytonic', 'pythonic', 'typhonic'],
     ['elands', 'ladens', 'naleds', 'sendal'],
     ['bast', 'bats', 'stab', 'tabs'],
     ['limes', 'miles', 'slime', 'smile'],
     ['calorie', 'cariole', 'coalier', 'loricae'],
     ['earth', 'hater', 'heart', 'rathe'],
     ['cornute', 'counter', 'recount', 'trounce'],
     ['eloins', 'insole', 'lesion', 'oleins'],
     ['doors', 'odors', 'ordos', 'roods'],
     ['early', 'layer', 'leary', 'relay'],
     ['cantered', 'crenated', 'decanter', 'recanted'],
     ['pouter', 'roupet', 'troupe', 'uptore'],
     ['drogue', 'gourde', 'rogued', 'rouged'],
     ['looter', 'retool', 'rootle', 'tooler'],
     ['angst', 'gnats', 'stang', 'tangs'],
     ['retest', 'setter', 'street', 'tester'],
     ['acts', 'cast', 'cats', 'scat'],
     ['islets', 'istles', 'sliest', 'stiles'],
     ['censoring', 'consigner', 'necrosing', 'reconsign'],
     ['biers', 'birse', 'bries', 'ribes'],
     ['moste', 'motes', 'smote', 'tomes'],
     ['otters', 'rottes', 'tortes', 'toters'],
     ['pasties', 'patsies', 'petsais', 'tapises'],
     ['nips', 'pins', 'snip', 'spin'],
     ['cleared', 'creedal', 'declare', 'relaced'],
     ['aids', 'dais', 'sadi', 'said'],
     ['lefter', 'refelt', 'reflet', 'telfer'],
     ['carpets', 'preacts', 'precast', 'spectra'],
     ['estrus', 'russet', 'surest', 'tusser'],
     ['merest', 'meters', 'metres', 'retems'],
     ['chanters', 'snatcher', 'stancher', 'tranches'],
     ['herons', 'honers', 'nosher', 'senhor'],
     ['moorwort', 'rootworm', 'tomorrow', 'wormroot'],
     ['maes', 'mesa', 'same', 'seam'],
     ['hips', 'phis', 'pish', 'ship'],
     ['cirrose', 'corries', 'crosier', 'orrices'],
     ['parsers', 'raspers', 'sparers', 'sparser'],
     ['erethic', 'etheric', 'heretic', 'techier'],
     ['center', 'centre', 'recent', 'tenrec'],
     ['capes', 'paces', 'scape', 'space'],
     ['egers', 'grees', 'reges', 'serge'],
     ['entree', 'eterne', 'retene', 'teener'],
     ['canoers', 'coarsen', 'corneas', 'narcose'],
     ['brunets', 'bunters', 'burnets', 'subrent'],
     ['lapsed', 'padles', 'pedals', 'pleads'],
     ['artiness', 'retsinas', 'stainers', 'stearins'],
     ['owners', 'resown', 'rowens', 'worsen'],
     ['abreacts', 'bearcats', 'cabarets', 'cabresta'],
     ['anosmic', 'camions', 'maniocs', 'masonic'],
     ['baritone', 'obtainer', 'reobtain', 'taborine'],
     ['sett', 'stet', 'test', 'tets'],
     ['paints', 'patins', 'pintas', 'ptisan'],
     ['diester', 'dieters', 'reedits', 'resited'],
     ['derives', 'deviser', 'diverse', 'revised'],
     ['stew', 'tews', 'west', 'wets'],
     ['cruses', 'curses', 'cusser', 'sucres'],
     ['rawest', 'tawers', 'waster', 'waters'],
     ['ephas', 'heaps', 'phase', 'shape'],
     ['alef', 'feal', 'flea', 'leaf'],
     ['meter', 'metre', 'remet', 'retem'],
     ['devein', 'endive', 'envied', 'veined'],
     ['presplit', 'ripplets', 'stippler', 'tipplers'],
     ['looters', 'retools', 'rootles', 'toolers'],
     ['contours', 'cornutos', 'croutons', 'outscorn'],
     ['bagel', 'belga', 'gable', 'gleba'],
     ['ryot', 'tory', 'troy', 'tyro'],
     ['arbored', 'boarder', 'broader', 'reboard'],
     ['misparted', 'preadmits', 'predatism', 'spermatid'],
     ['deliver', 'livered', 'relived', 'reviled'],
     ['onsets', 'setons', 'stenos', 'stones'],
     ['adders', 'dreads', 'readds', 'sadder'],
     ['construe', 'counters', 'recounts', 'trounces'],
     ['dangles', 'glandes', 'lagends', 'slanged'],
     ['enterer', 'reenter', 'terreen', 'terrene'],
     ['evilness', 'liveness', 'veinless', 'vileness'],
     ['gastrin', 'gratins', 'ratings', 'staring'],
     ['actioner', 'anoretic', 'creation', 'reaction'],
     ['censual', 'lacunes', 'launces', 'unlaces'],
     ['skating', 'staking', 'takings', 'tasking'],
     ['doubter', 'obtrude', 'outbred', 'redoubt'],
     ['cratering', 'recrating', 'retracing', 'terracing'],
     ['insetter', 'interest', 'sternite', 'trientes'],
     ['airshed', 'dashier', 'hardies', 'shadier'],
     ['pays', 'pyas', 'spay', 'yaps'],
     ['drail', 'laird', 'liard', 'lidar'],
     ['karn', 'knar', 'nark', 'rank'],
     ['drape', 'padre', 'pared', 'raped'],
     ['cantor', 'carton', 'contra', 'craton'],
     ['eringos', 'ignores', 'regions', 'signore'],
     ['derrises', 'desirers', 'dressier', 'residers'],
     ['ingress', 'resigns', 'signers', 'singers'],
     ['duramen', 'manured', 'maunder', 'unarmed'],
     ['ires', 'reis', 'rise', 'sire'],
     ['rillets', 'stiller', 'tillers', 'trellis'],
     ['layerings', 'searingly', 'syringeal', 'yearlings'],
     ['chores', 'cosher', 'ochers', 'ochres'],
     ['goers', 'gores', 'gorse', 'ogres'],
     ['ferlie', 'liefer', 'refile', 'relief'],
     ['minuets', 'minutes', 'mistune', 'mutines'],
     ['santol', 'stanol', 'talons', 'tolans'],
     ['piecers', 'pierces', 'precise', 'recipes'],
     ['strow', 'trows', 'worst', 'worts'],
     ['irks', 'kirs', 'kris', 'risk'],
     ['cassene', 'encases', 'seances', 'senecas'],
     ['ruinate', 'taurine', 'uranite', 'urinate'],
     ['aeroducts', 'ceratodus', 'croustade', 'educators'],
     ['camelids', 'decimals', 'declaims', 'medicals'],
     ['filters', 'lifters', 'stifler', 'trifles'],
     ['albs', 'bals', 'labs', 'slab'],
     ['burbles', 'lubbers', 'rubbles', 'slubber'],
     ['pensters', 'pertness', 'presents', 'serpents'],
     ['melters', 'remelts', 'resmelt', 'smelter'],
     ['gunshot', 'hognuts', 'noughts', 'shotgun'],
     ['arcked', 'carked', 'dacker', 'racked'],
     ['seitan', 'tenias', 'tineas', 'tisane'],
     ['resilver', 'revilers', 'silverer', 'sliverer'],
     ['gnarliest', 'integrals', 'reslating', 'triangles'],
     ['spirts', 'sprits', 'stirps', 'strips'],
     ['glisten', 'singlet', 'sniglet', 'tingles'],
     ['doper', 'pedro', 'pored', 'roped'],
     ['elisions', 'isolines', 'lionises', 'oiliness'],
     ['helos', 'holes', 'hosel', 'sheol'],
     ['parables', 'parsable', 'prebasal', 'sparable'],
     ['dangered', 'deranged', 'gandered', 'gardened'],
     ['crispate', 'paretics', 'picrates', 'practise'],
     ['intreats', 'nitrates', 'straiten', 'tertians'],
     ['ruinates', 'taurines', 'uranites', 'urinates'],
     ['dashes', 'sadhes', 'sashed', 'shades'],
     ['alerted', 'altered', 'related', 'treadle'],
     ['atresic', 'cristae', 'raciest', 'stearic'],
     ['ablest', 'bleats', 'stable', 'tables'],
     ['dangering', 'deranging', 'gandering', 'gardening'],
     ['cheaters', 'hectares', 'recheats', 'teachers'],
     ['agnostic', 'coasting', 'coatings', 'cotingas'],
     ['skater', 'strake', 'streak', 'takers'],
     ['lamps', 'palms', 'plasm', 'psalm'],
     ['hins', 'hisn', 'shin', 'sinh'],
     ['earl', 'lear', 'rale', 'real'],
     ['leap', 'pale', 'peal', 'plea'],
     ['alme', 'lame', 'male', 'meal'],
     ['argon', 'groan', 'orang', 'organ'],
     ['ceros', 'cores', 'corse', 'score'],
     ['airest', 'satire', 'striae', 'terais'],
     ['ewers', 'resew', 'sewer', 'sweer'],
     ['baiter', 'barite', 'rebait', 'terbia'],
     ['aplites', 'paliest', 'platies', 'talipes'],
     ['diol', 'idol', 'lido', 'loid'],
     ['maches', 'sachem', 'samech', 'schema'],
     ['heirs', 'hires', 'shier', 'shire'],
     ['mense', 'mesne', 'neems', 'semen'],
     ['tetri', 'titer', 'titre', 'trite'],
     ['devisor', 'devoirs', 'visored', 'voiders'],
     ['dale', 'deal', 'lade', 'lead'],
     ['ahed', 'hade', 'haed', 'head'],
     ['sweat', 'tawse', 'twaes', 'waste'],
     ['asserter', 'reassert', 'serrates', 'terrases'],
     ['lineups', 'lupines', 'spinule', 'unpiles'],
     ['douser', 'roused', 'soured', 'uredos'],
     ['doters', 'sorted', 'stored', 'strode'],
     ['impress', 'premiss', 'simpers', 'spirems'],
     ['dries', 'resid', 'rides', 'sired'],
     ['weird', 'wider', 'wired', 'wried'],
     ['door', 'odor', 'ordo', 'rood'],
     ['cedarn', 'craned', 'dancer', 'nacred'],
     ['ceruses', 'recuses', 'rescues', 'secures'],
     ['haets', 'haste', 'hates', 'heats'],
     ['altar', 'artal', 'ratal', 'talar'],
     ['crakes', 'creaks', 'sacker', 'screak'],
     ['anthesis', 'shanties', 'sheitans', 'sthenias'],
     ['adits', 'ditas', 'staid', 'tsadi'],
     ['dearest', 'derates', 'redates', 'sedater'],
     ['bros', 'orbs', 'robs', 'sorb'],
     ['burse', 'rebus', 'rubes', 'suber'],
     ['arrested', 'retreads', 'serrated', 'treaders'],
     ['graplines', 'presignal', 'relapsing', 'spanglier'],
     ['kanes', 'skean', 'snake', 'sneak'],
     ['delivers', 'desilver', 'silvered', 'slivered'],
     ['alit', 'lati', 'tail', 'tali'],
     ['cratered', 'recrated', 'retraced', 'terraced'],
     ['rato', 'rota', 'taro', 'tora'],
     ['caper', 'crape', 'pacer', 'recap'],
     ['statin', 'taints', 'tanist', 'titans'],
     ['calo', 'coal', 'cola', 'loca'],
     ['ergo', 'goer', 'gore', 'ogre'],
     ['dieter', 'reedit', 'retied', 'tiered'],
     ['ancients', 'canniest', 'insectan', 'instance'],
     ['donators', 'odorants', 'tandoors', 'tornados'],
     ['aspersing', 'grapiness', 'preassign', 'repassing'],
     ['outskate', 'outtakes', 'stakeout', 'takeouts'],
     ['inapt', 'paint', 'patin', 'pinta'],
     ['nipas', 'pains', 'pians', 'pinas'],
     ['overs', 'roves', 'servo', 'verso'],
     ['centiare', 'creatine', 'increate', 'iterance'],
     ['detour', 'redout', 'routed', 'toured'],
     ['courantes', 'courtesan', 'nectarous', 'outrances'],
     ['marshes', 'mashers', 'shmears', 'smasher'],
     ['neuters', 'retunes', 'tenures', 'tureens'],
     ['artsy', 'satyr', 'stray', 'trays'],
     ['erections', 'neoterics', 'resection', 'secretion'],
     ['adsorb', 'boards', 'broads', 'dobras'],
     ['nonets', 'sonnet', 'tenons', 'tonnes'],
     ['ashless', 'hassels', 'hassles', 'slashes'],
     ['orts', 'rots', 'sort', 'tors'],
     ['pelters', 'petrels', 'respelt', 'spelter'],
     ['gateman', 'magenta', 'magnate', 'nametag'],
     ['emprises', 'impreses', 'premises', 'spiremes'],
     ['energies', 'energise', 'greenies', 'reseeing'],
     ['baker', 'brake', 'break', 'kebar'],
     ['cerusites', 'cerussite', 'curtesies', 'icteruses'],
     ['hordes', 'horsed', 'reshod', 'shored'],
     ['nest', 'nets', 'sent', 'tens'],
     ['ceratin', 'certain', 'creatin', 'tacrine'],
     ['intrude', 'turdine', 'untired', 'untried'],
     ['keirs', 'kiers', 'siker', 'skier'],
     ['aptly', 'patly', 'platy', 'typal'],
     ['bust', 'buts', 'stub', 'tubs'],
     ['filer', 'flier', 'lifer', 'rifle'],
     ['artless', 'lasters', 'salters', 'slaters'],
     ['aproned', 'operand', 'padrone', 'pandore'],
     ['asp', 'pas', 'sap', 'spa'],
     ['pederast', 'predates', 'repasted', 'trapesed'],
     ['cider', 'cried', 'dicer', 'riced'],
     ['posters', 'prestos', 'respots', 'stopers'],
     ['lino', 'lion', 'loin', 'noil'],
     ['enlists', 'listens', 'silents', 'tinsels'],
     ['gagster', 'gargets', 'stagger', 'taggers'],
     ['epistler', 'peltries', 'perlites', 'reptiles'],
     ['pointers', 'porniest', 'proteins', 'tropines'],
     ['ferlies', 'refiles', 'reflies', 'reliefs'],
     ['aginners', 'earnings', 'engrains', 'grannies'],
     ['rowths', 'throws', 'whorts', 'worths'],
     ['predries', 'presider', 'reprised', 'respired'],
     ['drawers', 'redraws', 'rewards', 'warders'],
     ['darters', 'retards', 'starred', 'traders'],
     ['pedalers', 'pleaders', 'relapsed', 'repleads'],
     ['misphrase', 'misshaper', 'samphires', 'seraphims'],
     ['dopers', 'pedros', 'prosed', 'spored'],
     ['oils', 'silo', 'soil', 'soli'],
     ['ousting', 'outings', 'outsing', 'tousing'],
     ['grantee', 'greaten', 'negater', 'reagent'],
     ['peels', 'peles', 'sleep', 'speel'],
     ['loopers', 'poolers', 'respool', 'spooler'],
     ['cereals', 'relaces', 'rescale', 'sclerae'],
     ['airs', 'rais', 'rias', 'sari'],
     ['engram', 'german', 'manger', 'ragmen'],
     ['acinar', 'arnica', 'carina', 'crania'],
     ['emit', 'item', 'mite', 'time'],
     ['lisping', 'pilings', 'sliping', 'spiling'],
     ['resows', 'serows', 'sowers', 'worses'],
     ['openest', 'pentose', 'posteen', 'poteens'],
     ['impaler', 'impearl', 'lempira', 'palmier'],
     ['helots', 'hostel', 'hotels', 'tholes'],
     ['capsule', 'scaleup', 'specula', 'upscale'],
     ['corselet', 'electors', 'electros', 'selector'],
     ['magister', 'migrates', 'ragtimes', 'sterigma'],
     ['ables', 'bales', 'blase', 'sable'],
     ['loess', 'loses', 'sloes', 'soles'],
     ['acarines', 'canaries', 'cesarian', 'sarcinae'],
     ['enterers', 'reenters', 'terreens', 'terrenes'],
     ['passive', 'pavises', 'pavisse', 'spavies'],
     ['arbelest', 'bleaters', 'restable', 'retables'],
     ['finders', 'friends', 'redfins', 'refinds'],
     ['coders', 'credos', 'decors', 'scored'],
     ['lament', 'mantel', 'mantle', 'mental'],
     ['spouts', 'stoups', 'tossup', 'uptoss'],
     ['ashlering', 'narghiles', 'nargilehs', 'shearling'],
     ['pest', 'pets', 'sept', 'step'],
     ['callers', 'cellars', 'recalls', 'scleral'],
     ['adores', 'oreads', 'sarode', 'soared'],
     ['enol', 'leno', 'lone', 'noel'],
     ['anglesite', 'galenites', 'gelatines', 'teaseling'],
     ['admires', 'misread', 'sedarim', 'sidearm'],
     ['logions', 'loosing', 'olingos', 'soloing'],
     ['citers', 'recits', 'steric', 'trices'],
     ['huts', 'shut', 'thus', 'tush'],
     ['christen', 'citherns', 'cithrens', 'snitcher'],
     ['gelatins', 'genitals', 'stealing', 'taglines'],
     ['reticles', 'sclerite', 'tiercels', 'triscele'],
     ['daunter', 'natured', 'unrated', 'untread'],
     ['felid', 'field', 'filed', 'flied'],
     ['biders', 'brides', 'debris', 'rebids'],
     ['rivets', 'stiver', 'strive', 'verist'],
     ['actioners', 'anoretics', 'creations', 'reactions'],
     ['limpers', 'prelims', 'rimples', 'simpler'],
     ['alerter', 'alterer', 'realter', 'relater'],
     ['emirs', 'mires', 'miser', 'rimes'],
     ['mhos', 'mosh', 'ohms', 'shmo'],
     ['boast', 'boats', 'botas', 'sabot'],
     ['hasping', 'pashing', 'phasing', 'shaping'],
     ['coder', 'cored', 'credo', 'decor'],
     ['cestos', 'cosets', 'cosset', 'escots'],
     ['aspire', 'paries', 'praise', 'spirea'],
     ['aether', 'heater', 'hereat', 'reheat'],
     ['depart', 'parted', 'petard', 'prated'],
     ['adder', 'dared', 'dread', 'readd'],
     ['amain', 'amnia', 'anima', 'mania'],
     ['carted', 'crated', 'redact', 'traced'],
     ['cadres', 'cedars', 'sacred', 'scared'],
     ['outgrins', 'outrings', 'rousting', 'tourings'],
     ['letters', 'settler', 'sterlet', 'trestle'],
     ['orpins', 'prions', 'prison', 'spinor'],
     ['alefs', 'false', 'fleas', 'leafs'],
     ['baiters', 'barites', 'rebaits', 'terbias'],
     ['alpinist', 'antislip', 'pintails', 'tailspin'],
     ['nereis', 'seiner', 'serein', 'serine'],
     ['stoker', 'stroke', 'tokers', 'trokes'],
     ['loons', 'nolos', 'snool', 'solon'],
     ['flowers', 'fowlers', 'reflows', 'wolfers'],
     ['agentries', 'gratinees', 'reseating', 'stingaree'],
     ['eaglet', 'gelate', 'legate', 'telega'],
     ['parings', 'parsing', 'rasping', 'sparing'],
     ['capitol', 'coalpit', 'optical', 'topical'],
     ['danger', 'gander', 'garden', 'ranged'],
     ['gnus', 'guns', 'snug', 'sung'],
     ['rouster', 'routers', 'tourers', 'trouser'],
     ['citrine', 'crinite', 'inciter', 'neritic'],
     ['depots', 'despot', 'posted', 'stoped'],
     ['pathoses', 'potashes', 'spathose', 'teashops'],
     ['conies', 'cosine', 'icones', 'oscine'],
     ['enlister', 'listener', 'reenlist', 'silenter'],
     ['hasped', 'pashed', 'phased', 'shaped'],
     ['elaterins', 'entailers', 'nearliest', 'treenails'],
     ['erst', 'rest', 'rets', 'tres'],
     ['uncarted', 'uncrated', 'underact', 'untraced'],
     ['petrale', 'pleater', 'prelate', 'replate'],
     ['cantors', 'cartons', 'contras', 'cratons'],
     ['gluier', 'ligure', 'reguli', 'uglier'],
     ['persistent', 'pinsetters', 'presentist', 'prettiness'],
     ['lories', 'oilers', 'oriels', 'reoils'],
     ['emails', 'mailes', 'mesial', 'samiel'],
     ['cerous', 'course', 'crouse', 'source'],
     ['bolar', 'boral', 'labor', 'lobar'],
     ['gush', 'hugs', 'sugh', 'ughs'],
     ['dentures', 'sederunt', 'underset', 'unrested'],
     ['diopter', 'dioptre', 'peridot', 'proteid'],
     ['algors', 'argols', 'gorals', 'largos'],
     ['cuneal', 'lacune', 'launce', 'unlace'],
     ['awned', 'dawen', 'dewan', 'waned'],
     ['bruise', 'buries', 'busier', 'rubies'],
     ['must', 'muts', 'smut', 'stum'],
     ['persalts', 'plasters', 'psalters', 'staplers'],
     ['pearled', 'pedaler', 'pleader', 'replead'],
     ['restive', 'sievert', 'veriest', 'verites'],
     ['aorist', 'aristo', 'ratios', 'satori'],
     ['ports', 'prost', 'sport', 'strop'],
     ['asker', 'eskar', 'rakes', 'saker'],
     ['ottars', 'stator', 'tarots', 'tortas'],
     ['evils', 'levis', 'lives', 'veils'],
     ['weirs', 'wires', 'wiser', 'wries'],
     ['phrases', 'seraphs', 'shapers', 'sherpas'],
     ['evil', 'live', 'veil', 'vile'],
     ['lier', 'lire', 'riel', 'rile'],
     ['almes', 'lames', 'males', 'meals'],
     ['donator', 'odorant', 'tandoor', 'tornado'],
     ['ateliers', 'earliest', 'leariest', 'realties'],
     ['entases', 'sateens', 'senates', 'sensate'],
     ['stover', 'strove', 'troves', 'voters'],
     ['chiels', 'chiles', 'chisel', 'liches'],
     ['ayes', 'easy', 'eyas', 'yeas'],
     ['coiners', 'cronies', 'orceins', 'recoins'],
     ['bores', 'brose', 'robes', 'sober'],
     ['cion', 'coin', 'coni', 'icon'],
     ['naps', 'pans', 'snap', 'span'],
     ['ankhs', 'hanks', 'khans', 'shank'],
     ['enduros', 'resound', 'sounder', 'undoers'],
     ['caterers', 'recrates', 'retraces', 'terraces'],
     ['catered', 'cerated', 'created', 'reacted'],
     ['despoil', 'diploes', 'dipoles', 'spoiled'],
     ['pars', 'raps', 'rasp', 'spar'],
     ['gast', 'gats', 'stag', 'tags'],
     ['lose', 'oles', 'sloe', 'sole'],
     ['insetters', 'interests', 'sternites', 'triteness'],
     ['salves', 'selvas', 'slaves', 'valses'],
     ['danker', 'darken', 'narked', 'ranked'],
     ['diesters', 'editress', 'resisted', 'sistered'],
     ['parental', 'parlante', 'paternal', 'prenatal'],
     ['cheeros', 'coheres', 'echoers', 'rechose'],
     ['haws', 'shaw', 'shwa', 'wash'],
     ['eels', 'else', 'lees', 'seel'],
     ['elastins', 'nailsets', 'salients', 'saltines'],
     ['horses', 'hosers', 'shoers', 'shores'],
     ['horste', 'others', 'reshot', 'throes'],
     ['bard', 'brad', 'darb', 'drab'],
     ['adepter', 'predate', 'retaped', 'tapered'],
     ['gaper', 'grape', 'pager', 'parge'],
     ['abortus', 'robusta', 'rubatos', 'tabours'],
     ['fates', 'feast', 'feats', 'fetas'],
     ['palterers', 'plasterer', 'prealters', 'replaster'],
     ['aperients', 'episterna', 'pistareen', 'sparteine'],
     ['erotism', 'moister', 'mortise', 'trisome'],
     ['bards', 'brads', 'darbs', 'drabs'],
     ['discounter', 'introduces', 'rediscount', 'reductions'],
     ['panties', 'patines', 'sapient', 'spinate'],
     ['pride', 'pried', 'redip', 'riped'],
     ['perries', 'prisere', 'reprise', 'respire'],
     ['flower', 'fowler', 'reflow', 'wolfer'],
     ['acids', 'asdic', 'cadis', 'caids'],
     ['neuter', 'retune', 'tenure', 'tureen'],
     ['carps', 'craps', 'scarp', 'scrap'],
     ['gentries', 'integers', 'reesting', 'steering'],
     ['merriest', 'miterers', 'rimester', 'triremes'],
     ['armet', 'mater', 'ramet', 'tamer'],
     ['algor', 'argol', 'goral', 'largo'],
     ['anils', 'nails', 'slain', 'snail'],
     ['finder', 'friend', 'redfin', 'refind'],
     ['kitsch', 'schtik', 'shtick', 'thicks'],
     ['acrasin', 'arnicas', 'carinas', 'sarcina'],
     ['oast', 'oats', 'stoa', 'taos'],
     ['entires', 'entries', 'retines', 'trienes'],
     ['miseats', 'misseat', 'samites', 'tamises'],
     ['falser', 'farles', 'ferals', 'flares'],
     ['damneder', 'demander', 'redemand', 'remanded'],
     ['imarets', 'maestri', 'misrate', 'smartie'],
     ['brute', 'buret', 'rebut', 'tuber'],
     ['abos', 'boas', 'obas', 'soba'],
     ['bakers', 'brakes', 'breaks', 'kebars'],
     ['atria', 'raita', 'riata', 'tiara'],
     ['dens', 'ends', 'send', 'sned'],
     ['cheat', 'tache', 'teach', 'theca'],
     ['enter', 'rente', 'terne', 'treen']
   ],
5: [
     ['stater', 'taster', 'taters', 'tetras', 'treats'],
     ['admen', 'amend', 'maned', 'menad', 'named'],
     ['assentor', 'santeros', 'senators', 'starnose', 'treasons'],
     ['arsenites', 'irateness', 'resinates', 'stearines', 'teariness'],
     ['antis', 'saint', 'satin', 'stain', 'tains'],
     ['antes', 'etnas', 'nates', 'neats', 'stane'],
     ['skate', 'stake', 'steak', 'takes', 'teaks'],
     ['ate', 'eat', 'eta', 'tae', 'tea'],
     ['respects', 'scepters', 'sceptres', 'specters', 'spectres'],
     ['resit', 'rites', 'tiers', 'tires', 'tries'],
     ['riot', 'roti', 'tiro', 'tori', 'trio'],
     ['cereus', 'ceruse', 'recuse', 'rescue', 'secure'],
     ['dearer', 'reader', 'reared', 'redear', 'reread'],
     ['ambled', 'bedlam', 'beldam', 'blamed', 'lambed'],
     ['halters', 'harslet', 'lathers', 'slather', 'thalers'],
     ['asset', 'easts', 'sates', 'seats', 'tasse'],
     ['assertor', 'assorter', 'oratress', 'reassort', 'roasters'],
     ['retests', 'setters', 'streets', 'tersest', 'testers'],
     ['camelid', 'claimed', 'decimal', 'declaim', 'medical'],
     ['carles', 'clears', 'lacers', 'scaler', 'sclera'],
     ['aidmen', 'daimen', 'maiden', 'median', 'medina'],
     ['loops', 'polos', 'pools', 'sloop', 'spool'],
     ['cruse', 'cures', 'curse', 'ecrus', 'sucre'],
     ['prides', 'prised', 'redips', 'spider', 'spired'],
     ['recused', 'reduces', 'rescued', 'secured', 'seducer'],
     ['meister', 'metiers', 'reemits', 'retimes', 'triseme'],
     ['actinons', 'canonist', 'contains', 'sanction', 'sonantic'],
     ['cions', 'coins', 'icons', 'scion', 'sonic'],
     ['derries', 'desirer', 'redries', 'resider', 'serried'],
     ['bromes', 'ombers', 'ombres', 'somber', 'sombre'],
     ['resaws', 'sawers', 'sewars', 'swears', 'wrasse'],
     ['lopers', 'polers', 'proles', 'sloper', 'splore'],
     ['argle', 'glare', 'lager', 'large', 'regal'],
     ['diet', 'dite', 'edit', 'tide', 'tied'],
     ['drupes', 'dupers', 'perdus', 'prudes', 'pursed'],
     ['prosiest', 'prosties', 'reposits', 'ripostes', 'triposes'],
     ['dales', 'deals', 'lades', 'lased', 'leads'],
     ['entrails', 'latrines', 'ratlines', 'retinals', 'trenails'],
     ['gilders', 'girdles', 'gliders', 'regilds', 'ridgels'],
     ['airns', 'naris', 'rains', 'ranis', 'sarin'],
     ['cheater', 'hectare', 'recheat', 'reteach', 'teacher'],
     ['earns', 'nares', 'nears', 'saner', 'snare'],
     ['granite', 'gratine', 'ingrate', 'tangier', 'tearing'],
     ['angrier', 'earring', 'grainer', 'rangier', 'rearing'],
     ['eath', 'haet', 'hate', 'heat', 'thae'],
     ['phrase', 'raphes', 'seraph', 'shaper', 'sherpa'],
     ['demireps', 'epiderms', 'impeders', 'premised', 'simpered'],
     ['arcuses', 'causers', 'cesuras', 'saucers', 'sucrase'],
     ['abiders', 'braised', 'darbies', 'seabird', 'sidebar'],
     ['certes', 'erects', 'resect', 'secret', 'terces'],
     ['hares', 'hears', 'rheas', 'share', 'shear'],
     ['hooters', 'reshoot', 'sheroot', 'shooter', 'soother'],
     ['deigns', 'design', 'dinges', 'signed', 'singed'],
     ['centiares', 'cisternae', 'creatines', 'iterances', 'nectaries'],
     ['drawer', 'redraw', 'reward', 'warder', 'warred'],
     ['escarps', 'parsecs', 'scrapes', 'secpars', 'spacers'],
     ['ervils', 'livers', 'livres', 'silver', 'sliver'],
     ['lister', 'liters', 'litres', 'relist', 'tilers'],
     ['agers', 'gears', 'rages', 'sager', 'sarge'],
     ['actors', 'castor', 'costar', 'scrota', 'tarocs'],
     ['loots', 'lotos', 'sotol', 'stool', 'tools'],
     ['apter', 'pater', 'peart', 'prate', 'taper'],
     ['mate', 'meat', 'meta', 'tame', 'team'],
     ['amen', 'mane', 'mean', 'name', 'nema'],
     ['drupe', 'duper', 'perdu', 'prude', 'urped'],
     ['erugos', 'grouse', 'rogues', 'rouges', 'rugose'],
     ['ascent', 'centas', 'enacts', 'secant', 'stance'],
     ['drones', 'redons', 'snored', 'sonder', 'sorned'],
     ['arts', 'rats', 'star', 'tars', 'tsar'],
     ['demerit', 'dimeter', 'merited', 'mitered', 'retimed'],
     ['deer', 'dere', 'dree', 'rede', 'reed'],
     ['ascot', 'coast', 'coats', 'costa', 'tacos'],
     ['plisse', 'slipes', 'speils', 'spiels', 'spiles'],
     ['merit', 'miter', 'mitre', 'remit', 'timer'],
     ['peins', 'penis', 'pines', 'snipe', 'spine'],
     ['eons', 'noes', 'nose', 'ones', 'sone'],
     ['delist', 'idlest', 'listed', 'silted', 'tildes'],
     ['amines', 'animes', 'inseam', 'mesian', 'semina'],
     ['arpents', 'entraps', 'parents', 'pastern', 'trepans'],
     ['spirt', 'sprit', 'stirp', 'strip', 'trips'],
     ['ryots', 'story', 'stroy', 'troys', 'tyros'],
     ['roust', 'routs', 'stour', 'torus', 'tours'],
     ['attunes', 'nutates', 'tautens', 'tetanus', 'unstate'],
     ['intreat', 'iterant', 'nattier', 'nitrate', 'tertian'],
     ['craals', 'lascar', 'rascal', 'sacral', 'scalar'],
     ['hector', 'rochet', 'rotche', 'tocher', 'troche'],
     ['irons', 'noirs', 'noris', 'ornis', 'rosin'],
     ['everts', 'revest', 'revets', 'verset', 'verste'],
     ['rowth', 'throw', 'whort', 'worth', 'wroth'],
     ['aggers', 'eggars', 'gagers', 'sagger', 'seggar'],
     ['lave', 'leva', 'vale', 'veal', 'vela'],
     ['late', 'tael', 'tale', 'teal', 'tela'],
     ['gilder', 'girdle', 'glider', 'regild', 'ridgel'],
     ['parleys', 'parsley', 'players', 'replays', 'sparely'],
     ['eros', 'ores', 'roes', 'rose', 'sore'],
     ['dineros', 'indorse', 'ordines', 'rosined', 'sordine'],
     ['editors', 'sortied', 'steroid', 'storied', 'triodes'],
     ['alien', 'aline', 'anile', 'elain', 'liane'],
     ['eaglets', 'gelates', 'legates', 'segetal', 'telegas'],
     ['alts', 'last', 'lats', 'salt', 'slat'],
     ['antsiest', 'instates', 'nastiest', 'satinets', 'titaness'],
     ['caners', 'casern', 'cranes', 'nacres', 'rances'],
     ['estop', 'pesto', 'poets', 'stope', 'topes'],
     ['deil', 'deli', 'diel', 'idle', 'lied'],
     ['argons', 'groans', 'orangs', 'organs', 'sarong'],
     ['aigrets', 'gaiters', 'seagirt', 'stagier', 'triages'],
     ['ailments', 'aliments', 'manliest', 'melanist', 'smaltine'],
     ['aginner', 'earning', 'engrain', 'grannie', 'nearing'],
     ['resow', 'serow', 'sower', 'swore', 'worse'],
     ['angered', 'derange', 'enraged', 'grandee', 'grenade'],
     ['eroding', 'groined', 'ignored', 'negroid', 'redoing'],
     ['attrites', 'rattiest', 'tartiest', 'titrates', 'tristate'],
     ['ariettes', 'iterates', 'teariest', 'treaties', 'treatise'],
     ['ableists', 'astilbes', 'bastiles', 'blasties', 'stabiles'],
     ['rackets', 'restack', 'retacks', 'stacker', 'tackers'],
     ['latrine', 'ratline', 'reliant', 'retinal', 'trenail'],
     ['arches', 'chares', 'chaser', 'eschar', 'search'],
     ['boaster', 'boaters', 'borates', 'rebatos', 'sorbate'],
     ['earing', 'gainer', 'reagin', 'regain', 'regina'],
     ['parroted', 'predator', 'prorated', 'protrade', 'teardrop'],
     ['algin', 'align', 'liang', 'ligan', 'linga'],
     ['designer', 'energids', 'redesign', 'reedings', 'resigned'],
     ['porters', 'presort', 'pretors', 'reports', 'sporter'],
     ['aper', 'pare', 'pear', 'rape', 'reap'],
     ['apes', 'apse', 'pase', 'peas', 'spae'],
     ['nows', 'owns', 'snow', 'sown', 'wons'],
     ['roset', 'rotes', 'store', 'tores', 'torse'],
     ['pastries', 'piasters', 'piastres', 'raspiest', 'traipses'],
     ['arpent', 'enrapt', 'entrap', 'parent', 'trepan'],
     ['ariels', 'resail', 'sailer', 'serail', 'serial'],
     ['fires', 'fries', 'frise', 'reifs', 'serif'],
     ['parers', 'parser', 'rapers', 'rasper', 'sparer'],
     ['alps', 'laps', 'pals', 'salp', 'slap'],
     ['dinger', 'engird', 'girned', 'reding', 'ringed'],
     ['diesel', 'ediles', 'elides', 'sedile', 'seidel'],
     ['sitter', 'tetris', 'titers', 'titres', 'triste'],
     ['arista', 'raitas', 'riatas', 'tarsia', 'tiaras'],
     ['amblers', 'blamers', 'lambers', 'marbles', 'rambles'],
     ['state', 'taste', 'tates', 'teats', 'testa'],
     ['rues', 'ruse', 'suer', 'sure', 'user'],
     ['aider', 'aired', 'deair', 'irade', 'redia'],
     ['partlets', 'platters', 'prattles', 'splatter', 'sprattle'],
     ['roost', 'roots', 'rotos', 'toros', 'torso'],
     ['pisser', 'prises', 'speirs', 'spiers', 'spires'],
     ['estops', 'pestos', 'posset', 'ptoses', 'stopes'],
     ['alipeds', 'elapids', 'lapides', 'palsied', 'pleiads'],
     ['rosiest', 'sorites', 'sorties', 'stories', 'trioses'],
     ['ambler', 'blamer', 'lamber', 'marble', 'ramble'],
     ['leapers', 'pleaser', 'presale', 'relapse', 'repeals'],
     ['altars', 'astral', 'ratals', 'talars', 'tarsal'],
     ['arenites', 'arsenite', 'resinate', 'stearine', 'trainees'],
     ['inserter', 'reinsert', 'reinters', 'rentiers', 'terrines'],
     ['aspires', 'paresis', 'parises', 'praises', 'spireas'],
     ['dates', 'sated', 'stade', 'stead', 'tsade'],
     ['orthoses', 'reshoots', 'sheroots', 'shooters', 'soothers'],
     ['resort', 'retros', 'roster', 'sorter', 'storer'],
     ['amps', 'maps', 'pams', 'samp', 'spam'],
     ['filets', 'fliest', 'flites', 'itself', 'stifle'],
     ['ouster', 'outers', 'routes', 'souter', 'stoure'],
     ['hist', 'hits', 'shit', 'sith', 'this'],
     ['daters', 'derats', 'stared', 'trades', 'treads'],
     ['lores', 'loser', 'orles', 'roles', 'sorel'],
     ['part', 'prat', 'rapt', 'tarp', 'trap'],
     ['corsets', 'costers', 'escorts', 'scoters', 'sectors'],
     ['lameness', 'maleness', 'maneless', 'nameless', 'salesmen'],
     ['restrain', 'retrains', 'strainer', 'terrains', 'trainers'],
     ['insure', 'inures', 'rusine', 'urines', 'ursine'],
     ['list', 'lits', 'silt', 'slit', 'tils'],
     ['agrees', 'eagers', 'eagres', 'grease', 'ragees'],
     ['laveers', 'leavers', 'reveals', 'several', 'vealers'],
     ['elaters', 'realest', 'relates', 'reslate', 'stealer'],
     ['earless', 'leasers', 'resales', 'reseals', 'sealers'],
     ['ales', 'lase', 'leas', 'sale', 'seal'],
     ['aisled', 'deasil', 'ideals', 'ladies', 'sailed'],
     ['darnels', 'landers', 'relands', 'slander', 'snarled'],
     ['inserted', 'nerdiest', 'resident', 'sintered', 'trendies'],
     ['duels', 'dulse', 'leuds', 'ludes', 'slued'],
     ['karns', 'knars', 'narks', 'ranks', 'snark'],
     ['mares', 'marse', 'maser', 'reams', 'smear'],
     ['lapses', 'passel', 'saleps', 'sepals', 'spales'],
     ['awns', 'sawn', 'snaw', 'swan', 'wans'],
     ['aligner', 'engrail', 'nargile', 'realign', 'reginal'],
     ['atingle', 'elating', 'gelatin', 'genital', 'tagline'],
     ['leviers', 'relives', 'reviles', 'servile', 'veilers'],
     ['chaste', 'cheats', 'sachet', 'scathe', 'taches'],
     ['host', 'hots', 'shot', 'soth', 'tosh'],
     ['airless', 'resails', 'sailers', 'serails', 'serials'],
     ['bestir', 'bister', 'bistre', 'biters', 'tribes'],
     ['enviers', 'inverse', 'veiners', 'venires', 'versine'],
     ['inert', 'inter', 'niter', 'nitre', 'trine'],
     ['brutes', 'burets', 'buster', 'rebuts', 'tubers'],
     ['aliner', 'larine', 'linear', 'nailer', 'renail'],
     ['fetors', 'forest', 'fortes', 'foster', 'softer']
   ],
6: [
     ['ratos', 'roast', 'rotas', 'sorta', 'taros', 'toras'],
     ['bluest', 'bluets', 'bustle', 'butles', 'sublet', 'subtle'],
     ['heros', 'hoers', 'horse', 'hoser', 'shoer', 'shore'],
     ['entasis', 'nasties', 'seitans', 'sestina', 'tansies', 'tisanes'],
     ['deposit', 'dopiest', 'podites', 'posited', 'sopited', 'topside'],
     ['easting', 'eatings', 'ingates', 'ingesta', 'seating', 'teasing'],
     ['frites', 'refits', 'resift', 'rifest', 'sifter', 'strife'],
     ['dearths', 'hardest', 'hardset', 'hatreds', 'threads', 'trashed'],
     ['easters', 'reseats', 'searest', 'seaters', 'teasers', 'tessera'],
     ['luster', 'lustre', 'result', 'rustle', 'sutler', 'ulster'],
     ['aster', 'rates', 'resat', 'stare', 'tares', 'tears'],
     ['destain', 'detains', 'instead', 'nidates', 'sainted', 'stained'],
     ['hassel', 'hassle', 'lashes', 'selahs', 'shales', 'sheals'],
     ['gapers', 'gasper', 'grapes', 'pagers', 'parges', 'sparge'],
     ['dater', 'derat', 'rated', 'tared', 'trade', 'tread'],
     ['mates', 'meats', 'satem', 'steam', 'tames', 'teams'],
     ['hales', 'heals', 'leash', 'selah', 'shale', 'sheal'],
     ['larees', 'leaser', 'reales', 'resale', 'reseal', 'sealer'],
     ['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced'],
     ['hectors', 'rochets', 'rotches', 'tochers', 'torches', 'troches'],
     ['recepts', 'respect', 'scepter', 'sceptre', 'specter', 'spectre'],
     ['deers', 'drees', 'redes', 'reeds', 'seder', 'sered'],
     ['caress', 'carses', 'crases', 'escars', 'scares', 'seracs'],
     ['bares', 'baser', 'bears', 'braes', 'saber', 'sabre'],
     ['eviler', 'levier', 'liever', 'relive', 'revile', 'veiler'],
     ['alert', 'alter', 'artel', 'later', 'ratel', 'taler'],
     ['riots', 'rotis', 'tiros', 'torsi', 'trios', 'trois'],
     ['parts', 'prats', 'sprat', 'strap', 'tarps', 'traps'],
     ['manos', 'mason', 'moans', 'monas', 'nomas', 'soman'],
     ['painters', 'pantries', 'pertains', 'pinaster', 'pristane', 'repaints'],
     ['gater', 'grate', 'great', 'retag', 'targe', 'terga'],
     ['girons', 'grison', 'groins', 'rosing', 'signor', 'soring'],
     ['pores', 'poser', 'prose', 'repos', 'ropes', 'spore'],
     ['cruet', 'curet', 'cuter', 'eruct', 'recut', 'truce'],
     ['stow', 'swot', 'tows', 'twos', 'wost', 'wots'],
     ['deils', 'delis', 'idles', 'isled', 'sidle', 'slide'],
     ['airts', 'astir', 'sitar', 'stair', 'stria', 'tarsi'],
     ['claroes', 'coalers', 'escolar', 'oracles', 'recoals', 'solacer'],
     ['notes', 'onset', 'seton', 'steno', 'stone', 'tones'],
     ['esters', 'reests', 'resets', 'serest', 'steers', 'steres'],
     ['leets', 'sleet', 'steel', 'stele', 'teels', 'teles'],
     ['aretes', 'easter', 'eaters', 'reseat', 'seater', 'teaser'],
     ['aiders', 'deairs', 'irades', 'raised', 'redias', 'resaid'],
     ['ardeb', 'barde', 'bared', 'beard', 'bread', 'debar'],
     ['esprit', 'priest', 'ripest', 'sprite', 'stripe', 'tripes'],
     ['aspirer', 'parries', 'praiser', 'rapiers', 'raspier', 'repairs'],
     ['piles', 'plies', 'slipe', 'speil', 'spiel', 'spile'],
     ['rosets', 'sorest', 'stores', 'torses', 'tosser', 'tsores'],
     ['canister', 'ceratins', 'cisterna', 'creatins', 'scantier', 'tacrines'],
     ['albas', 'baals', 'balas', 'balsa', 'basal', 'sabal'],
     ['estrange', 'grantees', 'greatens', 'negaters', 'reagents', 'sergeant'],
     ['deltas', 'desalt', 'lasted', 'salted', 'slated', 'staled'],
     ['inset', 'neist', 'nites', 'senti', 'stein', 'tines'],
     ['corset', 'coster', 'escort', 'rectos', 'scoter', 'sector'],
     ['petrous', 'posture', 'pouters', 'proteus', 'spouter', 'troupes'],
     ['parties', 'pastier', 'piaster', 'piastre', 'pirates', 'traipse'],
     ['lusters', 'lustres', 'results', 'rustles', 'sutlers', 'ulsters'],
     ['opts', 'post', 'pots', 'spot', 'stop', 'tops'],
     ['leasts', 'slates', 'stales', 'steals', 'tassel', 'teslas'],
     ['aligners', 'engrails', 'nargiles', 'realigns', 'signaler', 'slangier'],
     ['alerting', 'altering', 'integral', 'relating', 'tanglier', 'triangle'],
     ['aliens', 'alines', 'elains', 'lianes', 'saline', 'silane'],
     ['reigns', 'renigs', 'resign', 'sering', 'signer', 'singer'],
     ['paster', 'paters', 'prates', 'repast', 'tapers', 'trapes'],
     ['ashed', 'deash', 'hades', 'heads', 'sadhe', 'shade'],
     ['carpels', 'clasper', 'parcels', 'placers', 'reclasp', 'scalper'],
     ['palters', 'persalt', 'plaster', 'platers', 'psalter', 'stapler'],
     ['staw', 'swat', 'taws', 'twas', 'wast', 'wats'],
     ['reins', 'resin', 'rinse', 'risen', 'serin', 'siren'],
     ['alevin', 'alvine', 'valine', 'veinal', 'venial', 'vineal'],
     ['elints', 'enlist', 'inlets', 'listen', 'silent', 'tinsel'],
     ['realist', 'retails', 'saltier', 'saltire', 'slatier', 'tailers']
   ],
7: [
     ['cruets', 'cruset', 'curets', 'eructs', 'rectus', 'recuts', 'truces'],
     ['ares', 'arse', 'ears', 'eras', 'rase', 'sear', 'sera'],
     ['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes'],
     ['paste', 'pates', 'peats', 'septa', 'spate', 'tapes', 'tepas'],
     ['estrous', 'oestrus', 'ousters', 'sourest', 'souters', 'stoures', 'tussore'],
     ['gaster', 'gaters', 'grates', 'greats', 'retags', 'stager', 'targes'],
     ['diopters', 'dioptres', 'peridots', 'portside', 'proteids', 'riposted', 'topsider'],
     ['amens', 'manes', 'manse', 'means', 'mensa', 'names', 'nemas'],
     ['ester', 'reest', 'reset', 'steer', 'stere', 'terse', 'trees'],
     ['empires', 'emprise', 'epimers', 'imprese', 'premies', 'premise', 'spireme'],
     ['merits', 'mister', 'miters', 'mitres', 'remits', 'smiter', 'timers'],
     ['pinots', 'pintos', 'piston', 'pitons', 'points', 'postin', 'spinto'],
     ['resaw', 'sawer', 'sewar', 'sware', 'swear', 'wares', 'wears'],
     ['laves', 'salve', 'selva', 'slave', 'vales', 'valse', 'veals'],
     ['algins', 'aligns', 'lasing', 'liangs', 'ligans', 'lingas', 'signal'],
     ['peers', 'peres', 'perse', 'prees', 'prese', 'speer', 'spree'],
     ['doers', 'doser', 'redos', 'resod', 'rodes', 'rosed', 'sored'],
     ['arils', 'lairs', 'laris', 'liars', 'liras', 'rails', 'rials'],
     ['canter', 'carnet', 'centra', 'nectar', 'recant', 'tanrec', 'trance'],
     ['acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac'],
     ['aril', 'lair', 'lari', 'liar', 'lira', 'rail', 'rial'],
     ['aspen', 'napes', 'neaps', 'panes', 'peans', 'sneap', 'spean'],
     ['diols', 'idols', 'lidos', 'loids', 'sloid', 'soldi', 'solid'],
     ['angriest', 'astringe', 'ganister', 'gantries', 'granites', 'ingrates', 'rangiest'],
     ['canters', 'carnets', 'nectars', 'recants', 'scanter', 'tanrecs', 'trances'],
     ['ableist', 'albites', 'astilbe', 'bastile', 'bestial', 'blastie', 'stabile'],
     ['poster', 'presto', 'repots', 'respot', 'stoper', 'topers', 'tropes'],
     ['esprits', 'persist', 'priests', 'spriest', 'sprites', 'stirpes', 'stripes'],
     ['enosis', 'eosins', 'essoin', 'noesis', 'noises', 'ossein', 'sonsie'],
     ['nestor', 'noters', 'stoner', 'tenors', 'tensor', 'toners', 'trones'],
     ['elastin', 'entails', 'nailset', 'salient', 'saltine', 'slainte', 'tenails'],
     ['deist', 'diets', 'dites', 'edits', 'sited', 'stied', 'tides'],
     ['aridest', 'astride', 'diaster', 'disrate', 'staider', 'tardies', 'tirades'],
     ['leapt', 'lepta', 'palet', 'petal', 'plate', 'pleat', 'tepal'],
     ['artiest', 'artiste', 'attires', 'iratest', 'ratites', 'striate', 'tastier'],
     ['armets', 'master', 'maters', 'matres', 'ramets', 'stream', 'tamers'],
     ['lavers', 'ravels', 'salver', 'serval', 'slaver', 'velars', 'versal'],
     ['emits', 'items', 'metis', 'mites', 'smite', 'stime', 'times'],
     ['ariled', 'derail', 'dialer', 'laired', 'railed', 'redial', 'relaid'],
     ['caret', 'carte', 'cater', 'crate', 'react', 'recta', 'trace'],
     ['arrest', 'rarest', 'raster', 'raters', 'starer', 'tarres', 'terras'],
     ['ardebs', 'bardes', 'beards', 'breads', 'debars', 'sabred', 'serdab'],
     ['drapes', 'padres', 'parsed', 'rasped', 'spader', 'spared', 'spread']
   ],
8: [
     ['peris', 'piers', 'pries', 'prise', 'ripes', 'speir', 'spier', 'spire'],
     ['earings', 'erasing', 'gainers', 'reagins', 'regains', 'reginas', 'searing', 'seringa'],
     ['aspers', 'parses', 'passer', 'prases', 'repass', 'spares', 'sparse', 'spears'],
     ['arles', 'earls', 'lares', 'laser', 'lears', 'rales', 'reals', 'seral'],
     ['enters', 'nester', 'renest', 'rentes', 'resent', 'tenser', 'ternes', 'treens'],
     ['carets', 'cartes', 'caster', 'caters', 'crates', 'reacts', 'recast', 'traces'],
     ['ates', 'east', 'eats', 'etas', 'sate', 'seat', 'seta', 'teas'],
     ['lapse', 'leaps', 'pales', 'peals', 'pleas', 'salep', 'sepal', 'spale']
   ],
9: [
     ['anestri', 'antsier', 'nastier', 'ratines', 'retains', 'retinas', 'retsina', 'stainer', 'stearin'],
     ['capers', 'crapes', 'escarp', 'pacers', 'parsec', 'recaps', 'scrape', 'secpar', 'spacer'],
     ['estrin', 'inerts', 'insert', 'inters', 'niters', 'nitres', 'sinter', 'triens', 'trines'],
     ['palest', 'palets', 'pastel', 'petals', 'plates', 'pleats', 'septal', 'staple', 'tepals']
   ],
10: [
      ['least', 'setal', 'slate', 'stale', 'steal', 'stela', 'taels', 'tales', 'teals', 'tesla']
    ],
11: [
      ['alerts', 'alters', 'artels', 'estral', 'laster', 'ratels', 'salter', 'slater', 'staler', 'stelar', 'talers']
    ],
12: [
      ['apers', 'apres', 'asper', 'pares', 'parse', 'pears', 'prase', 'presa', 'rapes', 'reaps', 'spare', 'spear']
    ]
  };
